#################
#  ItsOnlyCole  #
#  QuteBrowser  #
#    Config     #
#################

# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'w': 'session-save',
             'q': 'close',
             'qa': 'quit',
             'wq': 'quit --save',
             'wqa': 'quit --save',
             'aw': 'open aw',
             'yt': 'open yt',
             'sr': 'open sr',
             'reddit': 'open https://www.reddit.com',
             'youtube': 'open https://www.youtube.com',
             'pbsc': 'open https://www.palmbeachstate.edu',
             'bb': 'open https://www.palmbeachstate.blackboard.com',
             'blackboard': 'open https://www.palmbeachstate.blackboard.com',
             'bookmarks': 'open qute://bookmarks/',
             'hangoutsW': 'open https://hangouts.google.com/?authuser=1',
             'hangoutsP': 'open https://hangouts.google.com/?authuser=2'
            }

# Automatically start playing `<video>` elements. Note: On Qt < 5.11,
# this option needs a restart and does not support URL patterns.
# Type: Bool
c.content.autoplay = False
c.downloads.location.remember = False
c.downloads.location.directory = '/home/itsonlycole/Downloads/'
c.url.open_base_url = True
c.completion.open_categories = ["history"]
c.url.searchengines = {'DEFAULT': 'https://duckduckgo.com/?q={}',
                       'aw': 'https://wiki.archlinux.org/?search={}',
                       'yt': 'https://youtube.com/results?search_query={}',
                       'sr': 'https://www.reddit.com/r/{}',
                       'google': 'https://www.google.com/search?q={}'
                      }
c.input.insert_mode.auto_load = True
c.tabs.position = 'top'
c.tabs.show = 'switching'
c.tabs.show_switching_delay = 3000

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')
